# Generated by Django 2.1 on 2019-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='长网址')),
                ('short_link', models.CharField(max_length=16, verbose_name='短链接')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
        ),
    ]
