# Generated by Django 2.1 on 2019-04-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '网址映射', 'verbose_name_plural': '网址映射'},
        ),
        migrations.AlterModelTable(
            name='link',
            table='link_map',
        ),
    ]
